name: Deploy

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  BASE_USERS_PASS_ENCODING_SECRET: 706fca9c2d605726cecf37e04a3be17f6c5855abbad85ac88be4fa4486b29d35nd

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest tests

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: cr.yandex/crp14m9keoja3jtgii9e/zinchenkomig/base_users:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.AUTH_TOKEN }}
          command_timeout: 15m
          script: |
            if cd backend; then git pull; else git clone https://github.com/zinchenkomig/base-users-backend.git backend; cd backend; fi
            cd k8s
            KUBECONFIG=/etc/rancher/k3s/k3s.yaml helm upgrade backend scratch-app/ -i